apiVersion: v1alpha1
kind: VirtualMachine

metadata:
  name: ubuntu

spec:
  cpu: 1
  memory: 1Gi

  bootLoader:
    linux:
      kernel: ./focal-server-cloudimg-arm64-vmlinuz-generic
      initialRamdisk: ./focal-server-cloudimg-arm64-initrd-generic

  disks:
    - path: ./focal-server-cloudimg-arm64-raw.img

  networks:
    - type: nat

  cloudInit:
    instanceMetadata:
      instance_id: ubuntu
      local_hostname: ubuntu

    userData:
      ssh_authorized_keys:
        - your_ssh_public_key

    networkConfiguration:
      version: 2
      ethernets:
        id0:
          match:
            name: enp*
          dhcp4: true
          dhcp6: true
