builds:
  - id: vmkit
    main: ./cmd/vmkit
    binary: vmkit
  - id: vmkitd
    main: ./cmd/vmkitd
    binary: vmkitd

brews:
  - tap:
      owner: adnsio
      name: homebrew-tap
    commit_author:
      name: adnsio
      email: hello@adns.io
    description: Spin up Linux VMs with QEMU
    homepage: https://github.com/adnsio/vmkit
